import type { Metadata } from "next";

import "@/styles/globals.css";
import HeaderMain from "@/components/header/header-main";
import { Providers } from "./providers";
import { ReduxProvider } from "./providers/redux-provider";

export const metadata: Metadata = {
  title: "Funny Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <ReduxProvider>
          <Providers>
            <div id="header">
              <HeaderMain />
            </div>
            <div id="page">{children}</div>
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
